# BOX CONFIGURATION
BLUE = (0, 0, 255)
PURPLE = (128, 0, 128)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

BOX_WIDTH = 150
BOX_HEIGHT = 150
BORDER_RADIUS = 15

# Boxes position indicator
TOP_POSITION = "top"
RIGHT_POSITION = "right"
DOWN_POSITION = "down"
LEFT_POSITION = "left"
CENTER_POSITION = "center"

# Boxes frequencies
TOP_FREQ = 15  # HZ
RIGHT_FREQ = 13  # HZ
DOWN_FREQ = 11  # HZ
LEFT_FREQ = 9  # HZ

POSITIONS = [TOP_POSITION, RIGHT_POSITION, DOWN_POSITION, LEFT_POSITION]

freq = [TOP_FREQ, RIGHT_FREQ, DOWN_FREQ, LEFT_FREQ]

FREQUENCIES_DICT = {
    TOP_POSITION: TOP_FREQ,
    RIGHT_POSITION: RIGHT_FREQ,
    DOWN_POSITION: DOWN_FREQ,
    LEFT_POSITION: LEFT_FREQ
}

# SESSION CONFIGURATION
PREPARATION_TIME = 1
STIMULATION_TIME = 1
REST_TIME = 1
